# Ablation: no soft prompt, no cfg
model:
  # Set this to your checkpoint under ./ckpt
  checkpoint: ckpt/pmhcdiff_v2.pt


# bond_predictor: ckpt/bondpred.pt

sample:
  seed: 2023
  batch_size: 32
  # num_mols: 100
  resample: False
  save_traj_prob: 0.02
  guidance_scale: 0.25

dataset:
  name: pmhc_sample
  root: ./data/flex_pmhc
  path_dict:
    struct: pdb_pmhc_radius10.0_num100089.pickle
    # struct: pdb_pmhc_mhc_all_num1.pickle
    esm: esm_pmhc_radius10.0_num100089.pickle
    # esm: esm_pmhc_mhc_all_num1.pickle
    esm_avg: esm_pmhc_radius10.0_num100089_avg.pickle
    # esm_avg: esm_pmhc_mhc_all_num1_avg.pickle
    summary: full_dataset.csv
    processed: processed_sample_3.lmdb
  use_data: pmhc # 'pmhc' or 'peptide'
  sample_num_per_mhc: 128
  force_reload: False
  init_with_real_mhc: True # whether to init MHC with real structure. Otherwise, noise.
  
transform:
  use_mask_node: False
  use_mask_edge: False

chem:
  atomic_numbers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  mol_bond_types: [1]